title: certnotes.github.io
description: A blog and portfolio site focusing on the intersection of technology, social sciences, and humanities.
permalink: /posts/:title/
markdown: kramdown
exclude:
  - README.md

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-octicons

remote_theme: jekyll/minima

minima:
  skin: auto
  show_excerpts: true
  hide_site_feed_link: true

pinned_repos:
  - linux-cyber
  - data-AI-eng
  - BA-PO-econ
  - open-banking-lakehouse
